BOT_USE_EMAIL = False
DISCORD_BOT_EMAIL = "<<Discord email address>>"
DISCORD_BOT_PASSWORD = "<<Discord Password>>"
DISCORD_BOT_TOKEN = "RAINBOWDASHISTHEBESTPONYEVER"

MYSQL_IP = "127.0.0.1"
MYSQL_PORT = 3306
MYSQL_DATABASE = "Cloudsdale"
MYSQL_USERNAME = "root"
MYSQL_PASSWORD = "verysecretmuchwow"

REQUESTS_ENABLED = True

BOT_ADMINS = [00000000000, 00000000001]
